# Generated by Django 5.0.6 on 2024-07-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('AR', 'article'), ('NW', 'news')], default='AR', max_length=2),
        ),
    ]
